### ISSUE TITLE
throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by damianobarbati** [JaKXz/stylelint-webpack-plugin#111]
Help!

error
```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at eachParent (/Users/damz/Desktop/react-app/node_modules/browserslist/index.js:65:18)
    at getStat (/Users/damz/Desktop/react-app/node_modules/browserslist/index.js:79:12)
    at browserslist (/Users/damz/Desktop/react-app/node_modules/browserslist/index.js:188:15)
    at Browsers.parse (/Users/damz/Desktop/react-app/node_modules/stylelint/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/damz/Desktop/react-app/node_modules/stylelint/node_modules/autoprefixer/lib/browsers.js:52:30)
    at Object.<anonymous> (/Users/damz/Desktop/react-app/node_modules/stylelint/lib/utils/isAutoprefixable.js:19:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/damz/Desktop/react-app/node_modules/stylelint/lib/rules/at-rule-no-vendor-prefix/index.js:3:26)
```
package.json
```
"browserslist": [
    "chrome 58"
],

"stylelint": {
    "extends": [
        "stylelint-config-standard",
        "stylelint-config-sass-guidelines"
    ],
    "rules": {
        "indentation": 4,
        "order/properties-alphabetical-order": null,
        "no-missing-end-of-source-newline": null,
        "selector-list-comma-newline-after": null,
        "max-nesting-depth": null,
        "selector-pseudo-class-no-unknown": [
            true,
            {
                "ignorePseudoClasses": [
                    "global",
                    "local"
                ]
            }
        ]
    }
},
```
versions
```
"stylelint-config-sass-guidelines": "^3.0.1",
"stylelint-config-standard": "^17.0.0",
"stylelint-scss": "^1.4.4",
"stylelint-webpack-plugin": "^0.9.0",
"webpack": "^3.3.0",
```

**Comment by JaKXz** [comment]
@damianobarbati sorry for the very late response... I think your issue is not the result of this plugin, though. Feel free to provide more info & reopen if you are still seeing this problem.
