### ISSUE TITLE
Error: Unkonwn node type import

### ISSUE THREAD

**Issue by MatissJanis** [JaKXz/stylelint-webpack-plugin#113]
Upgrading to v0.9.0 from v0.8.0 causes this error to appear.

```
Error: Unkonwn node type import
    at /Users/matiss/kasko/friday-web-app/node_modules/stylelint-no-unsupported-browser-features/node_modules/doiuse/lib/detect-feature-use.js:152:19
    at Root.each (/Users/matiss/kasko/friday-web-app/node_modules/stylelint-webpack-plugin/node_modules/postcss-less/node_modules/postcss/lib/container.js:114:22)
    at Detector.node (/Users/matiss/kasko/friday-web-app/node_modules/stylelint-no-unsupported-browser-features/node_modules/doiuse/lib/detect-feature-use.js:137:13)
    at Detector.process (/Users/matiss/kasko/friday-web-app/node_modules/stylelint-no-unsupported-browser-features/node_modules/doiuse/lib/detect-feature-use.js:163:12)
    at Object.postcss (/Users/matiss/kasko/friday-web-app/node_modules/stylelint-no-unsupported-browser-features/node_modules/doiuse/lib/doiuse.js:40:23)
    at postCssPlugin (/Users/matiss/kasko/friday-web-app/node_modules/stylelint-no-unsupported-browser-features/index.js:35:27)
    at Promise.resolve.then (/Users/matiss/kasko/friday-web-app/node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/lintSource.js:161:9)
    at <anonymous>```

**Comment by MatissJanis** [comment]
After doing some research I've found that LESS's `@import` statements introduce this error.

**Comment by JaKXz** [comment]
@MatissJanis sorry for the delayed reply - it is actually the responsibility of stylelint itself to parse through your `.less` files so you will need to make sure it's configured correctly. TBH this is the main reason I've been hesitant on supporting less files by default in this plugin, which simply calls stylelint's `lint` function on the files you have listed in the options.
