### ISSUE TITLE
Undefined rule rule-empty-line-before

### ISSUE THREAD

**Issue by Regaddi** [JaKXz/stylelint-webpack-plugin#74]
Hey,

I'm currently facing this Error in my webpack build:

```
Error: Undefined rule rule-empty-line-before
    at module.exports (node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at Object.keys.forEach.ruleName (node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/augmentConfig.js:276:13)
    at Array.forEach (native)
    at normalizeAllRuleSettings (node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/augmentConfig.js:272:29)
    at augmentConfigBasic.then.then.then.then.augmentedConfig (node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/augmentConfig.js:81:12)
```

In my package.json I've defined those related packages:

```
{
  ...
  "devDependencies": {
    "autoprefixer": "^6.7.6",
    "babel": "^6.23.0",
    "babel-cli": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.4.0",
    "babel-plugin-istanbul": "^4.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.22.0",
    "babel-runtime": "^6.23.0",
    "babel-template": "^6.23.0",
    "babel-types": "^6.23.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "chai-spies": "^0.7.1",
    "change-case": "^3.0.1",
    "clean-webpack-plugin": "^0.1.15",
    "css-loader": "~0.27.1",
    "ejs": "^2.5.6",
    "ejs-loader": "^0.3.0",
    "enzyme": "^2.7.1",
    "esdoc": "^0.5.2",
    "esdoc-es7-plugin": "0.0.3",
    "eslint": "^3.17.1",
    "eslint-loader": "^1.6.3",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-mocha": "^4.8.0",
    "eslint-plugin-react": "^6.10.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.1",
    "git-hooks": "^1.1.8",
    "html-loader": "^0.4.5",
    "html-webpack-plugin": "^2.28.0",
    "jsdom": "^9.11.0",
    "json-loader": "^0.5.4",
    "karma": "^1.5.0",
    "karma-bamboo-reporter": "^0.1.2",
    "karma-chai": "^0.1.0",
    "karma-chai-as-promised": "^0.1.2",
    "karma-chai-spies": "^0.1.4",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-firefox-launcher": "^1.0.1",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.2",
    "karma-phantomjs-launcher": "^1.0.3",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.2",
    "less": "^2.7.2",
    "less-loader": "^3.0.0",
    "markdown-loader": "^2.0.0",
    "mocha": "^3.2.0",
    "mocha-jsdom": "^1.1.0",
    "mockery": "^2.0.0",
    "nock": "^9.0.9",
    "node-libs-browser": "^2.0.0",
    "node-sass": "^4.5.0",
    "npm-check-updates": "^2.10.3",
    "npm-run-all": "^4.0.2",
    "null-loader": "^0.1.1",
    "phantomjs-polyfill": "0.0.2",
    "postcss-loader": "^1.3.3",
    "postcss-url": "^5.1.2",
    "promise-loader": "^1.0.0",
    "prompt": "^1.0.0",
    "raw-loader": "^0.5.1",
    "react-addons-test-utils": "^15.4.2",
    "react-hot-loader": "^3.0.0-beta.6",
    "report-viewer": "^0.3.3",
    "requirejs": "^2.3.3",
    "sass-loader": "^6.0.3",
    "style-loader": "^0.13.2",
    "stylelint": "^7.9.0",
    "stylelint-config-standard": "^16.0.0",
    "stylelint-order": "^0.3.0",
    "stylelint-selector-bem-pattern": "^1.0.0",
    "stylelint-webpack-plugin": "^0.7.0",
    "url-loader": "^0.5.8",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1"
  },
  ...
}
```

This issue somehow occured, when I updated my packages.
I know, that stylelint introduced `rule-empty-line-before` in version `7.9.0`.
`stylelint-webpack-plugin` references to `^7.7.0` in its `package.json`.

Any hints on this?

**Comment by Regaddi** [comment]
Well, obviously the error ist referencing to `node_modules/stylelint-webpack-plugin/node_modules/stylelint` which has been downloaded in version `7.7.1`...

**Comment by JaKXz** [comment]
@Regaddi which version of npm are you using? perhaps try the old `rm -rf node_modules && npm cache clear && npm install`?

**Comment by Regaddi** [comment]
Hey, I installed with yarn. You could probably define stylelint as a peerDependency. This way the users defined version of stylelint should be used. I'll give it another shot with your suggestion.

**Comment by JaKXz** [comment]
@Regaddi see:
https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/package.json#L32-L33

I was hoping re-resolving your packages would solve that for you, since `7.9.0` is within the `^7.7.0` range.

**Comment by yangshun** [comment]
`rm -rf node_modules && yarn install` worked for me (in my case I was using Yarn. Thanks! (:

**Comment by JaKXz** [comment]
I think I am going to close this now since v0.9.0 depends on stylelint >= 8.

Please open a new issue for any new problems.
